main: com.cavetale.survivalgames.SurvivalGamesPlugin
name: SurvivalGames

version: 0.1
api-version: 1.19

description: SurvivalGames mini game
authors: [ StarTux ]
website: https://cavetale.com

depend: [Mytems, Core, PlayerCache, AFK, Title, Fam]
softdepend: []

commands:

  survivalgames:
    aliases: [sg]
    permission: survivalgames.admin
    usage: |-
      /sg start <world>

permissions:

  survivalgames.admin:
    description: Use /sg
    default: op

  survivalgames.team:
    description: Use /t
    default: true
