main: com.cavetale.survivalgames.SurvivalGamesPlugin

name: SurvivalGames
description: SurvivalGames mini game
authors: [ StarTux ]
version: 0.1-SNAPSHOT
api-version: 1.17
website: https://cavetale.com
depend: [ Mytems, Core, GenericEvents, AFK ]
softdepend: []

commands:
  survivalgames:
    aliases: [sg]
    permission: survivalgames.admin
    usage: |-
      /sg start <world>

permissions:
  survivalgames.admin:
    description: Use /sg
    default: op
